### ISSUE TITLE
--sound switch cannot be used to specify an arbitrary sound file in the file system

### ISSUE THREAD

**Issue by Dziemborowicz** [Dziemborowicz/Hourglass-New#57]

**Comment by Dziemborowicz** [comment]
It's good enough to require the user to install custom sounds.

**Comment by chocmake** [comment]
Would there be any room to consider this at least for custom sounds already added to the root Hourglass directory?

I realized recently that due to a few re-occurring timers some alternate custom sound to differentiate them would be particularly useful. Already have a custom sound set globally for all timers but was hoping I might be able to change it via the launch options.

(Unless that's already supported and I missed something. I tried `--sound filename-here`, `--sound filename-here.mp3` and both returned errors)

**Comment by dziemborowicz** [comment]
No worries. :) Glad it works.

For other users who might stumble upon this, it already should work that if you add something like `My Sound.mp3` into the Hourglass directory, you should be able to specify that sound on the command line with `--sound "My Sound"`.
